### ISSUE TITLE
Black Theme

### ISSUE THREAD

**Issue by adorotiuk** [ankurk91/google-chat-electron#10]
Please add the black theme.

### Platform

google-chat-electron 2.0.2
Electron 12.0.2
linux 5.8.0-50-generic
Locale: en-US

**Comment by ankurk91** [comment]
https://github.com/ankurk91/google-chat-electron/issues/7

**Comment by brightsider** [comment]
@ankurk91 any news?
https://www.electronjs.org/ru/docs/latest/tutorial/dark-mode have you tried this?

**Comment by ankurk91** [comment]
The app does not need any special code.
Dark theme is already present in native Chat UI Now

https://gadgetstouse.com/blog/2021/08/31/enable-dark-mode-in-google-chat/
