### ISSUE TITLE
Feature Suggestion - Chat-Plus Chrome Extension

### ISSUE THREAD

**Issue by notsuhas** [ankurk91/google-chat-electron#102]
Hey, I love your app. I had a small suggestion to allow/add a chrome extension called [Chat-Plus for Google Chat](https://chrome.google.com/webstore/detail/chat-plus-for-google-chat/njkkenehdklkfdkmonkagaicllmnfcda).

This adds 2 features I would love to have:

- Quoted Replies
- Link to Message

**Comment by ankurk91** [comment]
https://github.com/ankurk91/google-chat-electron/issues/71

https://github.com/ankurk91/google-chat-electron/issues/57
