### ISSUE TITLE
Unable to run After upgrade to 2..18

### ISSUE THREAD

**Issue by yasirmturk** [ankurk91/google-chat-electron#108]
`brew upgrade google-chat-electron`
& 
`brew uninstall google-chat-electron && brew install google-chat-electron`
both result in this error 

“google-chat-electron” is damaged and can’t be opened. You should move it to the Bin.
<img width="275" alt="Screenshot 2022-08-08 at 09 22 10" src="https://user-images.githubusercontent.com/306691/183362482-f123005a-1a1b-4e2c-b672-858013614c5f.png">

**Comment by ankurk91** [comment]
I would rather stop supporting max-os.

Why don't you search for similar issues

**Comment by yasirmturk** [comment]
So seems like the problem is with brew configuration. I have M1 and brew downloads arm64 builds.  I manually downloaded x64 build and it works

**Comment by ankurk91** [comment]
https://github.com/ankurk91/google-chat-electron/issues/78
