### ISSUE TITLE
MacOS: quitting app from the dock just minizes the active window

### ISSUE THREAD

**Issue by Arasthel** [ankurk91/google-chat-electron#11]
Hi, I've been using this project for a few weeks since the official Google Chat app got discontinued and I really didn't want to have to switch to Chrome to use just a web app with good OS integration. So far, it's been great!

However, I noticed some strange behavior: the 'Quit' action when the dock icon is right clicked doesn't match the `Cmd+Q` quit shortcut, it just minizes the active window into a dock item. I attached a video to show the current behavior. It isn't an important issue, I believe most users would just use the keyboard shortcut, but I thought it deserved to be reported anyway.

Thank you for your work on getting this app working!

https://user-images.githubusercontent.com/480955/115992575-b268f100-a5ce-11eb-824e-6efde87b08b9.mov

**Comment by ankurk91** [comment]
@Arasthel 
I am aware of this behavior, the app behaves same on Linux OS, the idea was not never let the app close.
I will let user to quit from app by clicking on dock menu at-least on mac os.

I am no longer a mac user, but i will try to get  mac os running via [susomi](https://github.com/popey/sosumi-snap)

**Comment by ankurk91** [comment]
Fixed in v2.2.0
