### ISSUE TITLE
Error on each program startup

### ISSUE THREAD

**Issue by lanx73** [ankurk91/google-chat-electron#114]
```
ProcessUncleanExitError: DELETE command exited with code 1:

Errore: Impossibile trovare la chiave del Registro di sistema o il valore specificato.
    at mkErrorMsg (C:\Program Files\Google Chat Electron\resources\app.asar\node_modules\winreg\lib\registry.js:111:12)
    at ChildProcess.<anonymous> (C:\Program Files\Google Chat Electron\resources\app.asar\node_modules\winreg\lib\registry.js:771:10)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
```

---

google-chat-electron 2.19.0
Electron 21.0.1
win32 10.0.22621
Locale: it

**Comment by ankurk91** [comment]
The app wants to read the registry, please open the app with Admin.

**Comment by lanx73** [comment]
> The app wants to read the registry, please open the app with Admin.

Sorry, I had already tried but the problem occurred the same way.

**Comment by ankurk91** [comment]
Duplicate of
https://github.com/ankurk91/google-chat-electron/issues/81

**Comment by lanx73** [comment]
Quite sorry but... the error I reported is unquestionably a duplicate of a previous bug-report, but it does not seem to me to have been resolved; rather, it was tagged as a problem specific to a single user/PC.
However, this only happens if the app is disabled to start automatically when the user logs in: you can clearly see appear and disappear the "google-chat-electron" entry under "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run" in the Windows registry by turning on and off the auto-start option.
So it is not a lack of privileges to access the registry, as other electron-based apps also work properly and do not give such errors.

**Comment by ankurk91** [comment]
I can not fix the issue unless I reproduce it on my machine
