### ISSUE TITLE
google-chat-electron.app is damaged

### ISSUE THREAD

**Issue by nerolite** [ankurk91/google-chat-electron#116]
I am getting the following error after the most recent update via _Homebrew Cask_:

"google-chat-electron.app is damaged and can't be opened. You should move it to the Bin."

![2022-10-03_08-43-19](https://user-images.githubusercontent.com/6739079/193515833-b45e08bc-c071-4721-ac56-56b63de08ab7.png)

Google-chat-electron version:  2.19.0
OS version: MacOS Monterey 12.6 

Any idea of to resolve this?

**Comment by ankurk91** [comment]
please search existing issues

**Comment by nerolite** [comment]
Apologies, and thanks!

See [#78](https://github.com/ankurk91/google-chat-electron/issues/78) for a solution.
