### ISSUE TITLE
404 error on electronjs website

### ISSUE THREAD

**Issue by Xav83** [ankurk91/google-chat-electron#118]
Hi google-chat-electron devs, :slightly_smiling_face:

I am creating this issue to notify you that the link to the `electronjs` website, in the `About` section of this repository leads to a "Page not found" screen (https://www.electronjs.org/apps/google-chat-electron).

![Screenshot from 2022-10-11 20-54-07](https://user-images.githubusercontent.com/6787157/195175550-9a395a39-aa71-4151-b2ef-b5c61ec7c84c.png)

**Comment by ankurk91** [comment]
Thanks
