### ISSUE TITLE
[Ubuntu] 'ç' character showing as 'ć' inside google-chat-electron

### ISSUE THREAD

**Issue by lucasrmendonca** [ankurk91/google-chat-electron#120]
### Issue description
I'm currently using a US keyboard with my Ubuntu keyboard layout settings set as: `English (US, intl., with dead keys) en`. This enables me to write messages both in Portuguese and English. 

To write the Portuguese `ç` character with this keyboard layout I use the following key combination: `'` + `c` = `ç`
However, this works for every application expect google-chat-electron, which gives me this instead: `'` + `c` = `ć`

Do you know what might be happening?

### Platform

google-chat-electron 2.16.1
Electron 19.0.1
linux 5.15.0-48-generic
Locale: en-US

**Comment by ankurk91** [comment]
Sorry, I have no clue

**Comment by lucasrmendonca** [comment]
For anyone coming here for help in the future, an alternative is to type `right Alt` + `,` = `ç`
