### ISSUE TITLE
[Ubuntu] Can't disable "Demo badge count"

### ISSUE THREAD

**Issue by lucasrmendonca** [ankurk91/google-chat-electron#121]
### Issue description

Help, I've accidentally clicked on Help > Troubleshooting > Demo badge count

And now I can't make the badge count go away, it's stuck at 39 unread messages:

![ss](https://user-images.githubusercontent.com/5521917/197059907-8f231f05-9b7f-4425-8292-947ff8e95f23.png)

### Platform

google-chat-electron 2.16.1
Electron 19.0.1
linux 5.15.0-48-generic
Locale: en-US

**Comment by ankurk91** [comment]
Restart the app or unplug the power cable of your computer or change your computer motherboard
