### ISSUE TITLE
Compilation fails on openSUSE

### ISSUE THREAD

**Issue by V-Z** [ankurk91/google-chat-electron#124]
Hello,
I try to compile the app on openSUSE (also RPM-based, as RedHat). I have pnpm 2.25.1 and run into error:

```
$ pnpm install
/usr/lib/node_modules/pnpm/lib/node_modules/graceful-fs/polyfills.js:285
        if (cb) cb.apply(this, arguments)
                   ^

TypeError: cb.apply is not a function
    at /usr/lib/node_modules/pnpm/lib/node_modules/graceful-fs/polyfills.js:285:20
    at /usr/lib/node_modules/pnpm/lib/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (node:fs:200:5)

Node.js v19.0.0
```

I have zero experience with these apps, so I don't know how to proceed... :-( How to fix that?

Conversion of the DEB package using `sudo alien -rc google-chat-electron_2.19.0_amd64.deb` works, but, of course, native compilation would be better.

**Comment by ankurk91** [comment]
please use node-js v18.12.x and pnpm v7.x
