### ISSUE TITLE
An option to disable spell check would be nice.

### ISSUE THREAD

**Issue by kli0rf** [ankurk91/google-chat-electron#126]
Sorry for not reading through the src and suggesting a patch / pull request, but could we get this? `mainWindow.webContents.session.setSpellCheckerEnabled( false );`
Windows 7 client here, didn't try on Fedora or macOS yet, but i'm going to.

**Comment by ankurk91** [comment]
okay, i will consider this in next version

**Comment by kratochviljan** [comment]
Super, that was about the only thing that bothered me...
(I got around to writing it here today, but as always I'm second...)
Thank you.
