### ISSUE TITLE
No sound notification on Windows 10

### ISSUE THREAD

**Issue by ThePsyjo** [ankurk91/google-chat-electron#128]
Sound notifications are not played on Windows 10 when the window is out of focus. When the window has focus, notifications are played. I am using ther latest release for windows.

**Comment by ankurk91** [comment]
Please check existing similar issues

**Comment by ThePsyjo** [comment]
There are no existing similar issues. Similar ones I found do not mention window or window fokus.

**Comment by Atlaimond** [comment]
I believe it's a **Google-Chat** issue. This does the same thing to me in Linux, while I use Firefox browser too. I also experience this on my Android tablet. 
LOL 
I solved this issue, on my tablet, via setting up the system to play a specific sound when **Google Chat app** pushes notification. 
I downloaded it from here: https://youtu.be/D42fHhhFjPQ 
 
PS. Maybe as a feature could you add @ankurk91 ?
