### ISSUE TITLE
Cannot sign in to Google Chat with Electron

### ISSUE THREAD

**Issue by hihosterling** [ankurk91/google-chat-electron#129]
Hi,
I apologize, I am new to how GitHub works so this is most likely the wrong place to put this, but just in case...

There was a thread about not being able to use Electron to sign in to Google Chat.

Suggestions were:
1) Exit and reload
2) Toggle External Links Guard in Help->Troubleshooting

Neither worked for me, but signing in with my cell number instead of my email worked right away.

**Comment by ankurk91** [comment]
Please check existing similar issues
