### ISSUE TITLE
Unusual Usage - Account Temporarily Locked Down

### ISSUE THREAD

**Issue by ljden** [ankurk91/google-chat-electron#132]
Just installed v2.19 and attempted to log in. Got a notice that my account was temporarily locked. Not sure if it is directly related to the app or if it's just google being over cautious with new logins.
![image](https://user-images.githubusercontent.com/29705680/203955599-f965ab18-7184-4e2d-9900-b7ec8891c771.png)

Received an email warning me of the activity and asking if it was me. Reporting the activity as me unlocked the account.

**Comment by ankurk91** [comment]
Your are using a enterprise gmailaccount ? or personal?

**Comment by ljden** [comment]
Personal

**Comment by ankurk91** [comment]
I will try the fresh installation with my personal account and let you know.

**Comment by davidsedlar** [comment]
I've been using this app for a long while with the business gmail account, no issues. Yesterday I also tried to log in with my personal account and got the dreaded "This browser or app may not be secure." error, also noted in https://github.com/ankurk91/google-chat-electron/issues/52
  
After a couple of retries, restarting the PC, logging out of my Android phone chat app, ... Don't know what worked in the end but I was finally able to login. Google is really being super annoying, it's clear they're trying to make life difficult for people who don't use their approved app or Chrome.

**Comment by ankurk91** [comment]
Unfortunately there is no fix available.
Certainly this app will stop working soon.
🙂

**Comment by davidsedlar** [comment]
> Unfortunately there is no fix available. Certainly this app will stop working soon. 🙂

I have faith still. Hopefully Google sees that more clients is just a benefit to them. 🤞
