### ISSUE TITLE
No notification popup or sound on Windows 10

### ISSUE THREAD

**Issue by Rings4** [ankurk91/google-chat-electron#134]
Notification popups and sounds work on the native Google Chat app within chrome. I also get notification sounds within Gmail in Firefox. Yet this app doesn't produce any popups or sounds. 

Any assistance would be greatly appreciated as this is completely useless to me without any way of getting notifications, either audibly or visually. Thanks!

**Comment by ankurk91** [comment]
Please check existing similar issues

**Comment by Rings4** [comment]
> Please check existing similar issues

Oh, I already did. I didn't see any solutions, so I posted my issue. As well, unless I missed it, there isn't a single issue that mentions the lack of popup notification.

Do you have any solution you can link me to? I may have missed it.

**Comment by ankurk91** [comment]
You are reporting 2 issues.

Notification sound: there is a pinned issue.

No notification: I can not reproduce it, no one can reproduce it. If you can send me your PC via courier, may be i can look into issue. :)

Tip: Reinstall your Windows OS. Or Check your notification global settings or Open the app with Admin rights.

I have not used windows from past 8 years.
I do testing on VM, fresh installation Only

**Comment by Rings4** [comment]
> You are reporting 2 issues.
> 
> Notification sound: there is a pinned issue.
> 
> No notification: I can not reproduce it, no one can reproduce it. If you can send me your PC via courier, may be i can look into issue. :)
> 
> Tip: Reinstall your Windows OS. Or Check your notification global settings or Open the app with Admin rights.
> 
> I have not used windows from past 8 years. I do testing on VM, fresh installation Only

That's a bummer. Was really hoping to replace the google chrome plugin with your software, but it seems it has some issues that can't be solved.
