### ISSUE TITLE
Chrome user agent might be a slightly better idea

### ISSUE THREAD

**Issue by adrianjagielak** [ankurk91/google-chat-electron#14]
Hi,
I noticed in the latest releases this app uses the "Dynamic Firefox version in user agent" and I was wondering if it was a good idea? The electron is chromium based so if Google ever serves code based on user-agent (e.g. some obscure javascript API that works only on gecko/chromium) this firefox user agent might break something in this app down the road? It might be a better idea to use a chrome/chromium user agent corresponding to the Electron version used in builds.

**Comment by ankurk91** [comment]
v2.4.0 released

**Comment by adrianjagielak** [comment]
Nice!
