### ISSUE TITLE
Feature request:  File downloads from within App

### ISSUE THREAD

**Issue by vincentrozenberg** [ankurk91/google-chat-electron#19]
It would be great if the Google Meet window opens inside the app, or alternatively, as a popup in the app. Also file downloads; Now both the meet and file links opens a browser, which specifically is inconvenient if you use different accounts (let's say, Browser is defaulting to Account A, and Google-Chat-Electron is set to a different Google/Workspace account, the files and links open in the browser with the wrong user, and with the files it even prompts a 404).

**Comment by ankurk91** [comment]
Great idea, but does electron can handle the file download well?

**Comment by vincentrozenberg** [comment]
> Great idea, but does electron can handle the file download well?

I assume it does; I guess it is a matter of "catching" the "https://chat.google.com/u/0/api/get_attachment_url?" url, before it directs to the browser. Or a different way, via the "download link" in previews:
![image](https://user-images.githubusercontent.com/5941546/128688173-ebe1329b-e3c5-47f6-8121-d24c187c6162.png)

**Comment by vincentrozenberg** [comment]
Actually what i mean is, that it "saves to disk" via the app, not via the browser

**Comment by ankurk91** [comment]
I am already catching the download file URL and sending it to external browser.
https://github.com/ankurk91/google-chat-electron/blob/master/src/main/features/externalLinks.ts#L36

I can plan to download the files within the app, but having the google meet within the app requires too much efforts and testing.
I can imagine people will ask for whole google suite products to work inside this app. :laughing: 

I don't see myself free enough for any big feature before Jan 2022. :)

**Comment by vincentrozenberg** [comment]
Thanks for looking into it!

**Comment by ankurk91** [comment]
It has been more than 1 year since this issue, I could not find enough time to work on this.
