### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by kylegrieder** [ankurk91/google-chat-electron#20]
Besides the fact that the PWA is absolutely terrible, the other thing I really dislike about it (as opposed to the mobile apps) is the lack of a dark mode. I've tried injecting CSS via Stylus or other means, but the way the PWA classes are set up, it's quite difficult. A dark mode would be nice, so it matches the rest of my applications. I might actually do this myself, and submit a PR for it, just wanted to put it here as well.

**Comment by ankurk91** [comment]
Dark mode is already there, but is upto user choice.

Check the app menus, and enable the dark mode. Restart the app to apply.

**Comment by kylegrieder** [comment]
OH! I was looking at the menus in-app, I didn't look at the macos system menus. thanks!

**Comment by kylegrieder** [comment]
although... the dark mode is less than ideal. 
![CleanShot 2021-08-09 at 10 16 52@2x](https://user-images.githubusercontent.com/25424229/128739330-c2edabe2-5cca-4591-9ded-d0f415e6eb48.png)

**Comment by ankurk91** [comment]
What is your app version?

Are you using the latest version of the app?

**Comment by kylegrieder** [comment]
I just downloaded it today, app version 2.5.1

**Comment by ankurk91** [comment]
I will check the dark mode on my vm machine tomorrow and report back here.

BTW, we are using dark reader Chrome extension behind the scene.

The app auto downloads the extension from Chrome store and start using it. 

https://github.com/darkreader/darkreader

**Comment by kylegrieder** [comment]
I checked that out. Installed the extension to Chrome and loaded the PWA. Got the same result.

Although what is really interesting is I used CMD + R to reload this app (google-chat-electron) and now I'm getting complete dark mode: 
![CleanShot 2021-08-09 at 11 08 36@2x](https://user-images.githubusercontent.com/25424229/128745963-1dfdf33e-00d0-4a5a-8e9a-7d2dd0826bae.png)

**Comment by ankurk91** [comment]
Great news, Chrome extension are experimental in electron apps.

I am closing the issue now.

**Comment by kylegrieder** [comment]
Sounds good. thanks again for making this, really enjoying it so far.
