### ISSUE TITLE
Feature Request: auto send smart reply

### ISSUE THREAD

**Issue by kylegrieder** [ankurk91/google-chat-electron#22]
The smart reply buttons in a chat are really convenient, and I find myself using them frequently. I think though that an opportunity was missed when designing these. They should auto send when I click the button, as opposed to just entering the text into the text box. 
![CleanShot 2021-08-16 at 09 52 58@2x](https://user-images.githubusercontent.com/25424229/129592691-b014eeaf-d177-468b-a16d-2c79888d45b4.png)

**Comment by ankurk91** [comment]
I have no plans to alter the default behavior or the UX/UI.

Such hacks are hard to maintain.
