### ISSUE TITLE
[snap] Google Chat Error Message

### ISSUE THREAD

**Issue by UniqueNET** [ankurk91/google-chat-electron#23]
```
Error: ERR_FAILED (-2) loading 'file:///snap/google-chat-electron/21/usr/lib/google-chat-electron/resources/app.asar/src/offline/index.html'
    at rejectAndCleanup (electron/js2c/browser_init.js:213:985)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:213:1360)
    at Object.emit (events.js:315:20)
```

---

google-chat-electron 2.5.1
Electron 13.1.6
linux 5.11.0-25-generic
Locale: en-GB

**Comment by ankurk91** [comment]
Try to relaunch the app.

Can you share, what you were trying to do at that moment?
Do you see this error every time?

**Comment by UniqueNET** [comment]
Good day

I was trying to launch the app on my Laptop when I got that error message
but now all is fine.

Thank you in advance.

Kind Regards

Chaka Tekane
Network Consultant
UNIQUENET  RESOURCE (PTY) LTD
Business Contact +2781 241 0055
Personal Contact +2772 991 0383

E-mail : ***@***.***
              ***@***.***
              ***@***.***
Skype : chaka4m3

''We must always read Instructions Manual that is Word Of GOD(Bible)''
