### ISSUE TITLE
Dark mode option has gone missing from some days.

### ISSUE THREAD

**Issue by vipulkrishna19** [ankurk91/google-chat-electron#26]
I had this application in dark mode but from some days, that option is not there. I need this app in dark mode. Please fix the issue.

### Platform

google-chat-electron 2.6.0
Electron 13.2.1
linux 5.4.0-81-generic
Locale: en-GB

**Comment by ankurk91** [comment]
https://workspaceupdates.googleblog.com/2021/08/dark-mode-for-google-chat-on-web.html

it is comming soon to your to your desktop.
