### ISSUE TITLE
Add StartupWMClass line to .desktop

### ISSUE THREAD

**Issue by aia832003** [ankurk91/google-chat-electron#30]
In standard GNOME for Fedora and other variants the current desk top file results in two icons if added to the dock as a Favorite and app window is in focus.  Adding StartupWMClass=google-chat-electron to the file fixes the issue. Screenshots included.
![Screenshot-20210831095323-1600x900](https://user-images.githubusercontent.com/11007827/131534258-ba6f6296-412b-4012-99b0-fd553a21f600.png)
![Screenshot-20210831095241-952x799](https://user-images.githubusercontent.com/11007827/131534274-d3956a6a-75ef-4602-8a27-c09d23c940fc.png)

**Comment by aia832003** [comment]
Image of fixed dock layout.

![Screenshot-20210831104704-1600x900](https://user-images.githubusercontent.com/11007827/131534765-359c5d01-13a1-4d32-80db-2506b2424c89.png)

**Comment by ankurk91** [comment]
I will try to replicate the issue on Ubuntu 20 Gnome

**Comment by aia832003** [comment]
Thanks @ankurk91

**Comment by ankurk91** [comment]
I could not re-produce the issue on Ubuntu 20.4 GNOME.
The only change i have made is, moved the Ubuntu dock to bottom, everything else is default settings.
See screenshot.
![Screenshot from 2021-09-03 10-59-39](https://user-images.githubusercontent.com/6111524/131955307-cdbce84b-161b-4f34-babf-0065d2baaee4.png)

**Comment by aia832003** [comment]
Thank you Anur. This seems to only affect Fedora. I can reproduce on both my machines running Fedora 34. I also don't see it on Ubuntu-based distros like Pop and Elementary. I can confirm add the StartWMClass line in /var/lib/snapd/desktop/applications file fixes with Fedora on both machines.

**Comment by aia832003** [comment]
Can also confirm that each update overwrites the manual addition of the fixed line from .desktop file. Any way this can be added for Fedora users?

**Comment by ankurk91** [comment]
I could not find any proper way to alter the . desktop file when building snap package

**Comment by ankurk91** [comment]
Out of 2951 users (snapcraft), only 11 users are using this app on Fedora.
I don't see it worth putting efforts to fix this glitch
