### ISSUE TITLE
mac: App is not minimizable

### ISSUE THREAD

**Issue by mjabdulm** [ankurk91/google-chat-electron#34]
Hi,

I'm not able to minimise the app in Mac using "<command>+M" keys. 

Could you please look into this?

Thanks,
Abdul

**Comment by ankurk91** [comment]
Hi,

I have not done anything specific to this shortcut in code.

I will try my best to replicate this in VM.

What is your OS version?

**Comment by mjabdulm** [comment]
Hi Ankur,

Thanks for the response. I'm using Big Sur 11.6.

**Comment by ankurk91** [comment]
I don't have 11.6 in my VM.
I will try to ask my office mates to test the app on real machines

**Comment by mjabdulm** [comment]
Hi Anukr,

Thanks a lot. I can be a beta tester before you release it.

**Comment by ankurk91** [comment]
This will be fixed in next version

**Comment by mjabdulm** [comment]
Thanks, Ankur for the superfast fix
