### ISSUE TITLE
Open with ...

### ISSUE THREAD

**Issue by bsahane** [ankurk91/google-chat-electron#35]
Very Good Google Chat Application for Linux.

But it always ask "Open with ..." for Installed Browsers after click on Hyperlink
Even if Default Browser is configured.

Please resolve this issue Default Inapp browser is great but need to login after click on hyperlink.
So It will be very good for me to open links directly in default browser.

### Platform

google-chat-electron 2.7.0
Electron 14.0.0
linux 4.18.0-305.12.1.el8_4.x86_64
Locale: en-US

**Comment by ankurk91** [comment]
What is your linux distro?

**Comment by ankurk91** [comment]
I don't think that there is an issue with app.

**Comment by bsahane** [comment]
Hello Ankur,

Currently I'm using Red Hat Enterprise Linux 8.4.
Please find screenshots for your reference.

**Image1** regular link: 
![image](https://user-images.githubusercontent.com/3491929/133963152-6430d965-f64c-4d6e-aeb9-c2b7d3dfd20f.png)

**Image2** after click on link ask for Open With: 
![image](https://user-images.githubusercontent.com/3491929/133963347-8e29a221-a127-4f92-a70f-5771739a0ae3.png)

**Image3** Default Browser Setting: 

![image](https://user-images.githubusercontent.com/3491929/133963497-d7132748-9a7b-4f6a-9a4e-8c516b0655a4.png)

**Comment by ankurk91** [comment]
i am using standard electron method to open links

```
shell.openExternal(url);
```
https://www.electronjs.org/docs/api/shell

I can not download and setup each and every Linux destro, sorry.
