### ISSUE TITLE
Error trying to start Windows build

### ISSUE THREAD

**Issue by vico93** [ankurk91/google-chat-electron#36]
When I try to run the Windows build v2. 9.0 (after unpacking the .zip to a writable folder) I got this error on a dialog...

```
Unhandled Promise Rejection
Error:  (-3) loading 'https://accounts.google.com/signin/v2/identifier?passive=1209600&osid=1&continue=https%3A%2F%2Fmail.google.com%2Fchat%2Fu%2F0%2F&followup=https%3A%2F%2Fmail.google.com%2Fchat%2Fu%2F0%2F&flowName=GlifWebSignIn&flowEntry=ServiceLogin'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7486)
    at Object.failListener (node:electron/js2c/browser_init:165:7699)
    at Object.emit (node:events:394:28)
```

...and the following error on the program itself:
![image(1).png](https://user-images.githubusercontent.com/3485505/134547193-b33c054a-1b8e-49a9-a56c-a3aa0d311d4f.png)

What I'm doing wrong?

**Comment by ankurk91** [comment]
What is your OS, windows 10?

**Comment by vico93** [comment]
Windows 10 21H1 19043.1237 x64

**Comment by ankurk91** [comment]
I was unable to re-produce the issue.

I download the zip file from GitHub, extracted it to `Program Files`, was able to run and login into app without any error.

Edition: Windows 10 Pro x64 (in Virtual box)
Version: 2004
OS Build: 19041.264

**Comment by ankurk91** [comment]
I did a quick test on fresh Windows 10 Pro 21H1 (in Virtual Box), i don't see any error.

**Comment by vico93** [comment]
Strange. I just unzipped the folder to `%AppData%\GChat Desktop` and it keeps doing this error. I deleted the folder `%AppData%\google-chat-electron` (which is created when the application is first started) and the same error happens.

What i could tell to you is the machine i'm testing this have proxy settings enabled (just ip and port, no auth). Could this be the reason?

**Comment by ankurk91** [comment]
I will test it with proxy enabled.

Proxy should not crash the app, it may block the app from connecting to internet
