### ISSUE TITLE
Un-fork the repo

### ISSUE THREAD

**Issue by cdwertmann** [ankurk91/google-chat-electron#38]
Hi!

I've submitted a Homebrew cask for this app here:
https://github.com/Homebrew/homebrew-cask/pull/112094

However they are not accepting the package because this repository is labelled as a fork of another (abandoned?) repo. Would you consider removing the fork label?

Thanks!

**Comment by ankurk91** [comment]
i am not sure how to unfork the repo without loosing the starts and download count, please guide me if you have an idea

**Comment by cdwertmann** [comment]
This was the first hit on Google: https://ralphjsmit.com/unfork-github-repo/
Have you tried it? It doesn't mention anything about losing download count.

**Comment by ankurk91** [comment]
okay, i will try this method, and will post back here soon.

**Comment by ankurk91** [comment]
The ticket has been created, now i am waiting from GitHub team

**Comment by ankurk91** [comment]
The repo has been detached now.
