### ISSUE TITLE
snap: Corrupted files being uploaded when size is over 200MB

### ISSUE THREAD

**Issue by iamKunal** [ankurk91/google-chat-electron#4]
# Platform
App Version: 1.2.0
Installed via : snap
Electron version: 11.2.3
Platform: Linux, 5.8.0-43-generic, x64
OS: #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021
Locale: en-GB

# Problem

Google Chat UI in the browser fails to upload files > 200MB telling that it isn't supported, whereas the app uploads a partial file of some sort (which is corrupted).

**Comment by ankurk91** [comment]
I will try to re-produce it.

**Comment by iamKunal** [comment]
A similar issue is when dragging and dropping files from outside the users home directory (like `/tmp`), the app uploads a 0 byte file.
The issue might be with snap, as it may not allow going above `$HOME`, but an error message would be great.

**Comment by ankurk91** [comment]
Looks like it is the limitation of Google chat itself.

Open google chat in your browser, for example Firefox
https://chat.google.com
And try to upload a file larger than 200 MB
You will see a toast saying "File size must be less than 200 mb"

**Comment by iamKunal** [comment]
Yeah, I think the issue was not with the file size, I tried reproducing it but the app correctly gives the correct toast.

The issue is with uploading files from outside the home directory, whatever the file size may be.

**Comment by ankurk91** [comment]
> A similar issue is when dragging and dropping files from outside the users home directory (like /tmp), the app uploads a 0 byte file.
The issue might be with snap, as it may not allow going above $HOME, but an error message would be great.

The snap app only has access to user's home directory and removable media, i dont see any reason on grant system directories permission to app.

https://snapcraft.io/docs/system-files-interface

**Comment by ankurk91** [comment]
I have already defined `removable-media` as plugin in` snapcraft.yml`
According to docs; it should grant permission to `/media` and `/mnt` folder.

https://snapcraft.io/docs/removable-media-interface

It is strange to see that snap app is unable to read from `/media/my-test-drive` folder for me.

**Comment by ankurk91** [comment]
Looks like end user need to manfully grant the removable media permission with this command
```
sudo snap connect google-chat-electron:removable-media :removable-media
```
i will document this soon.

**Comment by iamKunal** [comment]
> > A similar issue is when dragging and dropping files from outside the users home directory (like /tmp), the app uploads a 0 byte file.
> > The issue might be with snap, as it may not allow going above $HOME, but an error message would be great.
> 
> The snap app only has access to user's home directory and removable media, i dont see any reason on granting system directories permission to app.
> 
> https://snapcraft.io/docs/system-files-interface

Yeah, but an error message/toast would be great, as it happens that it sends a 0 byte file when we drag and drop.

**Comment by ankurk91** [comment]
I could not reproduce the 0 byte file issue yet.

There is no way to detect if the file was not uploaded, as this app just load the `chat.google.com`, we are not building our own chat  interface here.
