### ISSUE TITLE
Unable to Sign-in with Google Smart Lock

### ISSUE THREAD

**Issue by katagaki** [ankurk91/google-chat-electron#40]
It seems like google-chat-electron is unable to use Bluetooth to enable sign in to a Google account using the Google Smart Lock app.

Is Bluetooth something supported by Electron?

### Steps to reproduce

1. Enable the Google Smart Lock app as a security key on a Google account.
2. Sign in to the Google account on google-chat-electron.

### Expected result

Google prompts for a security key, Google Smart Lock receives a notification, and upon opening the Google Smart Lock app, the website communicates with Bluetooth with the Google Smart Lock app to verify the sign-in.

### Actual result

Google prompts for a security key, Google Smart Lock receives a notification, but upon opening the Google Smart Lock app, neither the website nor the app responds to each other.

**Comment by ankurk91** [comment]
Are you using the app on linux with snap?
