### ISSUE TITLE
Add to Chocolatey / winget

### ISSUE THREAD

**Issue by AdamJCavanaugh** [ankurk91/google-chat-electron#42]
Consider packaging and pushing the Windows release for Chocolatey. I do not have practical experience with this, but a quick look through some documentation appears to show that this can all be done via PowerShell and that GitHub Actions can run PowerShell, which would allow for automated updates, once configured.

https://github.com/majkinetor/au appears to be the recommended option as far as Chocolatey updates goes.

https://www.dolthub.com/blog/2021-10-13-how-to-publish-winget-chocolatey-packages-with-github-actions/ details how another application (Dolt) used GitHub Actions to publish on both Chocolatey and winget

**Comment by AdamJCavanaugh** [comment]
If you feel this is a valid request (as I hope you are, based on the label), I'm willing to put in some (maybe all?) work on it.

**Comment by ankurk91** [comment]
I am working on inno setup installer already and would like to go for winget.

No i am not free.

**Comment by ankurk91** [comment]
Submitted to winget
https://github.com/microsoft/winget-pkgs/pull/55927

**Comment by ankurk91** [comment]
Chocolatey support has been added too.

https://github.com/ankurk91/google-chat-electron/pull/109
