### ISSUE TITLE
Clicking on an attachment opens up a new empty electron window before prompting to download

### ISSUE THREAD

**Issue by iamKunal** [ankurk91/google-chat-electron#5]
# Platform
App Version: 1.2.0
Installed via : snap
Electron version: 11.2.3
Platform: Linux, 5.8.0-43-generic, x64
OS: #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021
Locale: en-GB

# Problem

This is only a slight UI problem. Clicking an attachment/file in a conversation opens up a new blank window and after a few seconds, a dialog box appears for saving. The blank window isn't closed automatically.

**Comment by ankurk91** [comment]
I was able to reproduce the issue. Will try to fix it soon
