### ISSUE TITLE
Sound notification not working

### ISSUE THREAD

**Issue by markovic-nikola** [ankurk91/google-chat-electron#50]
Hi, 
Thank you for this app, and the work you have put in.

As the title says, I'm not hearing a notification sound when receiving new messages.
It does show the notification itself, but I'm not hearing the sound alert.

### Platform

google-chat-electron 2.13.0
Electron 16.0.1
linux 5.15.5-76051505-generic
Locale: en-US
GNOME Shell 40.4.0
OS: Pop!_OS 21.10

**Comment by ankurk91** [comment]
I can test this behavior on my Ubuntu 20.04 gnome, I will report back here

**Comment by ankurk91** [comment]
Tested on 2 VMs, Ubuntu 20.04 gnome and MacOS 10.15, 
There was no sound when a notification appears in app.

Need to find out if electron natively support this feature or not.

**Comment by markovic-nikola** [comment]
Yup, I can confirm the issue is happening on the macOS 12.0 as well.

**Comment by ankurk91** [comment]
Looks like this feature is not supported well by electron

https://www.electronjs.org/docs/latest/api/notification#playing-sounds

**Comment by snorbik** [comment]
Now it seems to be supported (not sure how the documentation looked in December)

https://www.electronjs.org/docs/latest/api/notification#playing-sounds

Can help you test it on Mac if you want ;)

**Comment by ankurk91** [comment]
This documentation is there from last 2 years :)

This app shows notification coming from renderer process, but this doc suggest to use background process.

I dont know why notification sound is so important for people, i keep my desktop notification on silent, since I can see them coming in my monitor right corner.
