### ISSUE TITLE
Feature: resolve/remove google redirect

### ISSUE THREAD

**Issue by dvaerum** [ankurk91/google-chat-electron#54]
First off, thanks for making this. It is a pain in the ass, to use Google Chat in the browser, but this makes it much better, so thanks 😃 

I was wondering it is possible to remove/resolve google redirect for all links posted in Google Chat

because every time I click a link inside Google Chat, I get send to this side in my browser
![image](https://user-images.githubusercontent.com/6872940/148183176-0fd0c491-01fa-4c2e-810f-cc9dd4396dfc.png)

**Comment by ankurk91** [comment]
I dont see this as a big issue, this is a security feature where google prefix the URLs shared on chat.
If someone shared malicious link, google can save you before getting hacked.

You can try installing this addon to clean the URLs
https://addons.mozilla.org/en-US/firefox/addon/clearurls/

**Comment by StreborStrebor** [comment]
I'm afraid I do think this is an issue.

The reason for me to use your wonderful app on my M1 Macbook is to not have Google Chat running as Chrome PWA and opening URLs in Chrome. I use Safari as default browser and want Chat links to open in Safari. Not having Chat running in Chrome is a welcome bonus.

But now I get this annoying redirect notice page every time I click on a link in Chat. 
And google by the looks of it tracks my click on the link. No thanks.

I would love it if you stripped the redirect and racking code form the external link URLs and reduce it to the originally shared URL. When running Chat in Safari (or any other browser), the user is not confronted with annoying page and the link loads as as intended (I'm sure Google still tracks tracks you, but does not annoy you with the redirect warning and simply send you to the URL).

I found a Safari extension that does do the trick (It works, on MacOS Ventura / Safari 16.1 even though it was last updated in 2021: https://github.com/Sh1d0w/clean-links ), but would love it if your app would do this, removing the necessity to use two apps to to get the job done.

**Comment by ankurk91** [comment]
You should not be afraid because you are already using a Google product.

This app will not change the default behavior
