### ISSUE TITLE
Incorrect release filenames for v2.13.1

### ISSUE THREAD

**Issue by mjeveritt** [ankurk91/google-chat-electron#55]
Whilst it looks like the pathname is correct for the 2.13.1 releases, the filenames refer to 2.13.0. Can you please update so that the right release is in the right path?! Thanks!

**Comment by ankurk91** [comment]
@mjeveritt 

Hey, thanks for reporting the issue, i have deleted the bogus release and tagged an new version which should be available to download a few minutes,
