### ISSUE TITLE
2.13.2 MacOS release prompting for upgrades

### ISSUE THREAD

**Issue by ericyanush** [ankurk91/google-chat-electron#56]
After downloading the latest 2.13.2 MacOS release, I'm being prompted for an update to 2.13.2. The 2.13.2 binary seems to be packaged with version 2.0.1.

<img width="268" alt="Screen Shot 2022-01-12 at 1 48 51 PM" src="https://user-images.githubusercontent.com/1020116/149211268-b34abdc9-27c0-4159-95a1-171d5b48eea4.png">

The Info.plist in the bundle however, does show 2.13.2 as the package version.

<img width="1378" alt="Screen Shot 2022-01-12 at 1 49 59 PM" src="https://user-images.githubusercontent.com/1020116/149211411-6548dd3e-2280-4360-810f-1746608c1da1.png">

**Comment by ankurk91** [comment]
Please quit from app completely.
And update to latest version, then launch the app.

**Comment by ericyanush** [comment]
@ankurk91, I did, several times. I even deleted, re-downloaded and replaced the bundle three times.

**Comment by ankurk91** [comment]
Are you installing the app via homebrew?

I will try to install the app and will post here soon

**Comment by ericyanush** [comment]
Installing via direct download from GitHub release, copying to /Applications/ and removing the quarantine attribute.

**Comment by ankurk91** [comment]
I was unable to reproduce the issue.
I am running mac os 10.15

![Screenshot from 2022-01-13 10-00-13](https://user-images.githubusercontent.com/6111524/149266273-68825046-a261-47d1-8f83-bb7d024718c0.png)
