### ISSUE TITLE
Feature request: add QUOTE shortcut

### ISSUE THREAD

**Issue by pesso82** [ankurk91/google-chat-electron#57]
A QUOTE shortcut action would be very very appreciated.

At this moment quote can be done only by copying text message to quote and writing 6 single quotes like 
`
``` text copied ```
`

Thanks

**Comment by jeremyjohn** [comment]
:+1: Yea something like this https://chrome.google.com/webstore/detail/google-chat-thread-links/aogkhbmeeckelbhfemleoajbglamokbc

**Comment by ankurk91** [comment]
This app does not support chrome extensions OR custom scripts for now.
