### ISSUE TITLE
v2.14.0 release vanished!

### ISSUE THREAD

**Issue by mjeveritt** [ankurk91/google-chat-electron#59]
Hi, I got the email notification about 2.14 being released with updated Electron, but it looks like it's had to be removed. Just wanted to check in, and find out ETA! :) Cheers!

**Comment by ankurk91** [comment]
The publishing  was not completed, so removed.

https://github.com/snapcore/action-publish/issues/23

i am waiting for the snap craft to fix the issue.

**Comment by mjeveritt** [comment]
Thanks!

**Comment by ankurk91** [comment]
Please check 2.14.2 release

**Comment by mjeveritt** [comment]
App Version: 2.14.2
Electron version: 17.0.0
Chrome version: 98.0.4758.74
Platform: Linux, 5.4.106-rt54-xanmod1-mje03rt, x64
OS: #9 SMP PREEMPT_RT Tue Mar 23 13:26:05 GMT 2021
Locale: en-GB

LGTM :) ty!
