### ISSUE TITLE
Feature Request: add support for loading chrome extensions

### ISSUE THREAD

**Issue by iamKunal** [ankurk91/google-chat-electron#6]
There are some useful extension the chrome web store that I miss after I moved to the electron client.
E.g. https://chrome.google.com/webstore/detail/google-chat-thread-links/aogkhbmeeckelbhfemleoajbglamokbc

It would be nice to either have their features available or allow people to load their own extensions (via https://www.electronjs.org/docs/tutorial/devtools-extension) even if supplied via the config folder.

**Comment by ankurk91** [comment]
Okay i will try to implement this feature soon.

**Comment by ankurk91** [comment]
@iamKunal 
The chrome extension you mention, is no longer working with new UI

**Comment by iamKunal** [comment]
> @iamKunal
> The chrome extension you mention, is no longer working with new UI

They are yet to merge a pr for the new ui https://github.com/upman/gchat-copy/issues/10

**Comment by iamKunal** [comment]
@ankurk91 What about tampermonkey support? The only issue might be adding scripts via the UI. For e.g. https://github.com/myreli/chat-extended

**Comment by ankurk91** [comment]
`tampermonkey` need user to add script, however electron does not have an address bar to show the extension icon

**Comment by iamKunal** [comment]
Just saw https://github.com/sentialx/electron-extensions
I also see they mention support for https://github.com/sentialx/electron-extensions/issues/22#issue-607045604

**Comment by ankurk91** [comment]
i am not in favor of loading extension from hard disk path, i am using this one
https://github.com/MarshallOfSound/electron-devtools-installer 
to install from chrome store using the id

**Comment by jwaiwit** [comment]
just share my tried (worst). after the browser loaded, try to inject the content js (used to with old chat) using  **window.webContents.executeJavaScript(customScript);**
`document.querySelectorAll('iframe[title="Chat content"]')[0].contentWindow.document.querySelectorAll("c-wiz[data-topic-id][data-local-topic-id]")
VM1157:1 Uncaught DOMException: Blocked a frame with origin "https://mail.google.com" from accessing a cross-origin frame.
    at <anonymous>:1:75`

After search, found that chrome-extension have privileges to run on all_frames option. 
I might be wrong. This is how far I can reached :D

**Comment by ankurk91** [comment]
I am closing this issue for several reasons

* Electron has experimental support for extensions
* This feature is not going to benefit mass number of users
* Extensions will cause app to consume more RAM and CPU
* Hard to debug and maintain
