### ISSUE TITLE
[kubuntu] Tray Icon "doesn't work"

### ISSUE THREAD

**Issue by emmandyar** [ankurk91/google-chat-electron#66]
So, english isn't my first language, so I didin't know how to write the title clearly, but basically what happens is the tray icon doesn't respond to any sort of clicking action, wether left, right, middle buttons.

The app is still working, because I see the notification dot on the icon and can call it from the launcher and it pops up again. Launched it from the console and I don't see any relevant messages (only something about a deprecation and dns)

Chat 2.14.2, installed via deb package
Kubuntu 21.10
KDE 5.24.0
KDE Framework 5.91.0

**Comment by ankurk91** [comment]
It is not easy for me download and test on each every version of Ubuntu.
Please try to re-install the app, or may be stick to LTS version of Ubuntu.

**Comment by ankurk91** [comment]
Closing due to unsupported OS

**Comment by emmandyar** [comment]
Welp I came to say I purged and reinstalled, then the menu came back. Was something specific to this machine, as I have 2 other kubuntu, one 21.10 and one LTS, on both the tray menu worked as expected.
