### ISSUE TITLE
[mac] Toggle dock icon on macos

### ISSUE THREAD

**Issue by willbutler** [ankurk91/google-chat-electron#72]
I've seen requests to turn off the menubar icon on the Mac, but would it possible to allow the app to run with _only_ the menubar icon when in the background? There are some other apps that run in the background that do this when you close the main window. Thanks!

**Comment by ankurk91** [comment]
Does electron support this ?

**Comment by willbutler** [comment]
Similar support was added to the Electron-based Signal desktop app: https://github.com/signalapp/Signal-Desktop/issues/2210.

**Comment by willbutler** [comment]
@ankurk91 Sorry for the confusion! The request was to be able to disable the dock icon completely. In other words, it would be great to _just_ have the icon in the menu bar without it taking up a spot in the dock.

**Comment by ankurk91** [comment]
The issue you have linked, it not related to hiding the dock icon, is it?

**Comment by willbutler** [comment]
Hmm. I think this PR better captures what I'm referring to: https://github.com/signalapp/Signal-Desktop/pull/3335.

**Comment by eazyAlf** [comment]
Hi there, this is actually what I have asked for before – to be able to hide it from the dock or from the active applications when switching between apps/windows (cmd + tab)

https://github.com/ankurk91/google-chat-electron/issues/44

i changed this in plist with plistbuddy:
`/usr/libexec/PlistBuddy -c 'Add :LSUIElement bool true' /Applications/google-chat-electron.app/Contents/Info.plist
`

only annoying thing is that it resets after every update and the menu bar isn't accessible anymore

> Hmm. I think this PR better captures what I'm referring to: [signalapp/Signal-Desktop#3335](https://github.com/signalapp/Signal-Desktop/pull/3335).
is this hard to integrate?
