### ISSUE TITLE
[mac] CMD+K shortcut is broken

### ISSUE THREAD

**Issue by aaronabl** [ankurk91/google-chat-electron#74]
### Platform

google-chat-electron 2.14.3
Electron 17.1.2
darwin 21.4.0
Locale: en-GB

For some reason, CMD+K shortcut no longer works and hitting the key combo just doesn't do anything.

**Comment by ankurk91** [comment]
I will check the shortcut and will let you know.

Meanwhile can you specify the exact information about your mac OS and version?

**Comment by aaronabl** [comment]
I'm on MacOS 12.3 Beta (21E5196i)

It was previously working fine on this version of MacOS if that helps.


Cheers,

*Aaron M.*
*CEO*
*AB Logistics*

*m: *+65 8812 9369
*w:* ablogistics.co

Sent via Superhuman ***@***.***>

**Comment by ankurk91** [comment]
Unfortunately i don't have Mac OS 12, i will test it on my VM (10.15) and will let you know.

BTW, CTRL+K shortcut is provided by Google Chat web interface and this app itself has nothing to do with it.

You may want to try the shortcut in your browser first.
https://mail.google.com/chat/u/0/

**Comment by aaronabl** [comment]
Hey Ankur,

I understand that, but not sure why it stopped working on the app.

The shortcut works fine on the browser.

*Aaron M.*
*CEO*
*AB Logistics*

*m: *+65 8812 9369
*w:* ablogistics.co

Sent via Superhuman ***@***.***>

**Comment by ankurk91** [comment]
I could not reproduce the issue on Mac OS 10.15.

**Comment by aaronabl** [comment]
I will try to re-install the app on Monday, see if that helps.

*Aaron M.*
*CEO*
*AB Logistics*

*m: *+65 8812 9369
*w:* ablogistics.co

Sent via Superhuman ***@***.***>

**Comment by aaronabl** [comment]
Hi Ankur,

Unfortunately, reinstalling the app also doesn't help with the shortcuts.
It seems that formatting text shortcuts work but the CMD+K or CMD+O, etc.
doesn't seem to be working.

I've recently gone out of beta and into MacOS 12.3 (21E230).

On app version 2.14.3.

*Aaron M.*
*CEO*
*AB Logistics*

*m: *+65 8812 9369
*w:* ablogistics.co

Sent via Superhuman ***@***.***>

**Comment by ankurk91** [comment]
I dont have a way to test the app on Mac OS 12 for now, i will try to upgrade my VM or will reach out to my office mates to test the app.

**Comment by hlynbech** [comment]
I have tested App Version: 2.14.3 in MacOS 12.2.1, and CMD-K is not working here. Surprisingly, CTRL-K is working and opens the expected dialog. Also, in the built-in help page in google-chat-electron, the keyboard shortcuts are correctly listed with CTRL in relevant cases.

However, this is not normal behaviour on Mac apps, and indeed if you open google chat in a chrome browser, CTRL-K does nothing but CMD-K opens the expected dialog. So it seems some logic has been applied in the web chat client to follow expected MacOS behaviour.
The expected keyboard shortcuts for MacOS is listed here: https://support.google.com/chat/answer/7649271?hl=en

App Version: 2.14.3
Electron version: 17.1.2
Chrome version: 98.0.4758.109
Platform: Darwin, 21.3.0, x64
OS: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
Locale: da

**Comment by ankurk91** [comment]
At-least one of the shortcut is working, glad to know.

We have overridden the User Agent string in this electron app, We are using Linux+Firefox user agent to spoof Google servers.
This may be the root cause of `CRTL` vs `CMD` misbehaviour.

I will test it more with different user agent soon.

Thanks for insights.

**Comment by ankurk91** [comment]
@aaronabl
Can you try the v2.14.4?
https://github.com/ankurk91/google-chat-electron/releases/tag/2.14.4

 i have removed the User agent string, Hope it will restore the Mac OS keyboard shortcuts.

**Comment by aaronabl** [comment]
Marvelous! It's working!

*Aaron M.*
*CEO*
*AB Logistics*

*m: *+65 8812 9369
*w:* ablogistics.co

Sent via Superhuman ***@***.***>

**Comment by hlynbech** [comment]
Yes, I can also confirm that it's working in 2.14.4!
