### ISSUE TITLE
Jump to present

### ISSUE THREAD

**Issue by feyzikesim** [ankurk91/google-chat-electron#75]
### Platform

google-chat-electron 2.14.3
Electron 17.1.2
linux 5.13.0-35-generic
Locale: en-US

When I'm viewing older messages, its hard to return back to present. I think that would be nice to have a "Jump to recent/present messages" button down there. Thank for your concern

**Comment by ankurk91** [comment]
Please contact google to introduce such feature.
This app does not control what appear inside the frame.
