### ISSUE TITLE
Not getting sound notifications

### ISSUE THREAD

**Issue by pylightt** [ankurk91/google-chat-electron#77]
### Not getting sound notifications

I'm getting sound notifications on my other apps, and all my notifications settings are turned on. It's just for Google Chat electron that I'm not getting them.

google-chat-electron 2.14.3
Electron 17.1.2
linux 5.13.0-35-generic
Locale: en-US

**Comment by ankurk91** [comment]
https://github.com/ankurk91/google-chat-electron/issues/65
