### ISSUE TITLE
[mac] The arm version seems not to work on M1

### ISSUE THREAD

**Issue by rizzoli** [ankurk91/google-chat-electron#78]
I have a MacBook Pro with an M! arm processor and I tried to install the updated version and I received a message that the google-chat-electron app is "damaged" upon launch.

**Comment by ankurk91** [comment]
You need to go to Preferences, then security, then Allow to Run the app.

The app does not have a certificate.
End user need to manually approve it to run.

I don't have M1 and can not verify it.

**Comment by ankurk91** [comment]
Ping @ericyanush

**Comment by rizzoli** [comment]
Yes, I did that. And after doing that I got that message. I have then reinstalled the x86 version which works fine. If I find some time I will try to download the source code and compile it.

**Comment by ericyanush** [comment]
I tested the 2.14.4 ARM64 release and didn't have any issues. Steps I took to install:

1. Download release
2. Move the app to the /Applications folder
3. Run the command `xattr -d com.apple.quarantine /Applications/google-chat-electron.app`

For reference I'm testing it on a 16" M1 Pro MacBook running macOS 12.3

**Comment by ankurk91** [comment]
Tnanks for confirming

**Comment by rizzoli** [comment]
I confirm that manually changing the attribute works. In my previous attempt I thought I enabled the app through the security tab in the preference pane, but that did not work. Thanks
