### ISSUE TITLE
Is there a Mac support?

### ISSUE THREAD

**Issue by mjabdulm** [ankurk91/google-chat-electron#8]
Hi,

Is it possible to compile this for Mac?

**Comment by ankurk91** [comment]
Hey,

I no longer a mac user but it should not be hard to add support for mac os. 

I will try to make the code compatible.

**Comment by mjabdulm** [comment]
Hi Ankur,

Thanks a lot for the update. Yes, I don’t want to use PWA app.

Cheers
Abdul

On 03-Apr-2021, at 11:51 AM, Ankur Kumar ***@***.***> wrote:


Hey,

I no longer a mac user but it should not be hard to add support for mac os.

I will try to make the code compatible.

**Comment by ankurk91** [comment]
@mjabdulm 

You can download the `google-chat-electron-darwin-x64.zip` file from 
https://github.com/ankurk91/google-chat-electron/releases

Follow installation instruction written in readme

**Comment by mjabdulm** [comment]
Hi Ankur,

Thanks a lot. It works perfectly fine. 

In my office environment, we use Okta,vmwareidentity for login. I’ve modified the externalLink function to handle this.

Cheers
Abdul

On 08-Apr-2021, at 10:20 AM, Ankur Kumar ***@***.***> wrote:


@mjabdulm <https://github.com/mjabdulm>
You can download the google-chat-electron-darwin-x64.zip file from
https://github.com/ankurk91/google-chat-electron/releases <https://github.com/ankurk91/google-chat-electron/releases>
Follow installation instruction written in readme
