### ISSUE TITLE
google-chat-electron-2.14.4-darwin-arm64 package is damaged

### ISSUE THREAD

**Issue by jasonmajor** [ankurk91/google-chat-electron#80]
Seems the 2.14.4 release zip file is fine, but the packaged application is damaged. I've tried a few different unzip tools including the built-in archive. I've also tried on 2 different M1 macs. same issue pops up:
“google-chat-electron.app” is damaged and can’t be opened. You should move it to the Trash.

macos 12.3 (21E230) Monterey
Apple Macbook pro m1 (2020) and Apple Macbook pro Max (late 2021)

Problem does not exist for intel release.

**Comment by ankurk91** [comment]
https://github.com/ankurk91/google-chat-electron/issues/78

Thanks for wasting my time
