### ISSUE TITLE
[Win 11] On every program start since 4 or 5 versions: ProcessUncleanExitError: DELETE command exited with code 1:

### ISSUE THREAD

**Issue by p3P4** [ankurk91/google-chat-electron#81]
Error:
```
Unhandled Promise Rejection
ProcessUncleanExitError: DELETE command exited with code 1:
FEHLER: Der angegebene Registrierungsschl�ssel bzw. Wert wurde nicht gefunden.
    at mkErrorMsg (C:/Program Files/Google Chat Electron/resources/app.asar/node_modules/winreg/lib/registry.js:111:12)
    at ChildProcess.<anonymous> (C:/Program Files/Google Chat Electron/resources/app.asar/node_modules/winreg/lib/registry.js:771:10)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```
Error in English (translated)
```
The specified registry key or value was not found
```

After acknowledging this error, the program starts and runs normal.

**Comment by ankurk91** [comment]
Please share more information.

App version:
Windows version:

When does the error appears, on first launch? on every launch?

FYI: The app need to write to Windows registery, make sure app has enough permissions.

**Comment by p3P4** [comment]
Hi,

App is 2.14.4 (I guess, the Problem exists since minimum 5 releases)
Win is Win11 21H2 22000.593

Error appears on EVERY start

Registry … ok - which keys? The app is started as normal user with normal permissions
Regulary installed as admin for sure.

Greets Peter

**Comment by ankurk91** [comment]
Okay, I will test the app on Windows 11 vm.

The app may need to write in registry to auto start on next boot.

**Comment by p3P4** [comment]
I do not use autostart, I start it manually …the error occurs on every manual start

**Comment by ankurk91** [comment]
Even if you don't use auto start feature, the app may need to access registry.

**Comment by ankurk91** [comment]
I installed the app on  a fresh vm
```
Windows 11 Pro
21H2
22000.194
```
and could not re-produce the issue

**Comment by p3P4** [comment]
Hi, 2.15 does produce the error on my system too … BUT only as user … not as admin!
Which Reg-Keys should be writable?

**Comment by ankurk91** [comment]
If you can read coffee script :)

https://github.com/Teamwork/node-auto-launch/blob/master/src/AutoLaunchWindows.coffee

**Comment by p3P4** [comment]
Looks like it needs only access to \HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run And I found it! The Problem only  occurs, if you disable autostart in settings (if enabled, all looks good).Possible cause: the key google-chat-electron in … CurrentVersion\Run does not exist, but the program expects it …  Von: Ankur KumarGesendet: Donnerstag, 7. April 2022 13:24An: ankurk91/google-chat-electronCc: p3P4; AuthorBetreff: Re: [ankurk91/google-chat-electron] [Win 11] On every program start since 4 or 5 versions: ProcessUncleanExitError: DELETE command exited with code 1: (Issue #81) If you can read coffee script :)https://github.com/Teamwork/node-auto-launch/blob/master/src/AutoLaunchWindows.coffee—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
