### ISSUE TITLE
[Ubuntu 20] Cannot start the application since the last release

### ISSUE THREAD

**Issue by Deuchnord** [ankurk91/google-chat-electron#82]
Hi

Since today's release, the application can't start anymore. Invoking from the command line gives the following error:

```
➜  ~ google-chat-electron 
ERROR: not connected to the gnome-3-34-1804 content interface.
```

I'm running Ubuntu 20.04 LTS, which uses GNOME 3.36.

**Comment by ankurk91** [comment]
Did you install the app via snap?

The app was working fine before today release?

**Comment by Deuchnord** [comment]
Yes, the app is installed via Snap. It worked perfectly yesterday;

**Comment by ankurk91** [comment]
Okay, I will debug it

**Comment by ankurk91** [comment]
Meanwhile can you uninstall the app and reinstall via command line?

**Comment by Deuchnord** [comment]
Sorry, just realized the app actually didn't upgrade itself :facepalm: 
For some reasons, the app didn't start anymore until I forced the upgrade.
