### ISSUE TITLE
Cannot open on MacBook Pro 2020 M1

### ISSUE THREAD

**Issue by Yeboster** [ankurk91/google-chat-electron#83]
Dear Ankurk91,
First of all thanks for this project, keep up the great work!

Unfortunately from the version [2.14.4](https://github.com/ankurk91/google-chat-electron/releases/tag/2.14.4), where you split the binaries between x64 and arm64, it doesn't open anymore because of the following error:

<img width="258" alt="'google-chat-electron.app' is damaged and can't be opened. You should move it to the Bin" src="https://user-images.githubusercontent.com/23556525/162144155-1ec5fea6-bbfc-496d-b139-2711c8354221.png">

I've downloaded the arm64 version and I'm using MacOs Monterey 12.0.1.

<img width="198" alt="Screenshot 2022-04-07 at 09 30 35" src="https://user-images.githubusercontent.com/23556525/162144541-30d28cd0-1eb0-49a1-b351-c9bfe0ad099d.png">

The issue is still there in version 2.15.0 arm64, but it works fine on 2.14.3. 
If you need some logs please give me some guidance and I'm happy to provide them.

EDIT: I've just discovered that the x64 version works well! It is probably because of Rosetta 2?

Have a great day!

**Comment by ankurk91** [comment]
https://github.com/ankurk91/google-chat-electron/issues/80

Thanks for wasting my time
