### ISSUE TITLE
[Win 10] Error during startup

### ISSUE THREAD

**Issue by shappix** [ankurk91/google-chat-electron#84]
```
Error: ERR_FAILED (-2) loading 'file://C:\Program Files\Google Chat Electron\resources\app.asar\src\offline\index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:402:35)
```

---

google-chat-electron 2.14.3
Electron 17.1.2
win32 10.0.19043
Locale: el

**Comment by shappix** [comment]
Hi Ankur,

I saw this error on first launch.

**Comment by ankurk91** [comment]
I will test this on my VM.

But i am sure i wont be able to reproduce it :)

**Comment by shappix** [comment]
I have "Auto Launch on Login" option enabled. The problem occurs during the first login in Windows and not at every launch of the google-chat-electron.

I use the same version of google-chat-electron on my desktop and my laptop, but the problem only occurs on my laptop.
Maybe is something wrong with my laptop. :)

**Comment by ankurk91** [comment]
Yup, get rid of Windows and switch to Linux
