### ISSUE TITLE
[mac] [brew] 2.15.1 damaged

### ISSUE THREAD

**Issue by snorbik** [ankurk91/google-chat-electron#88]
After updating to latest version 2.15.1 it breaks the app.

Your app google-chat-electron is damaged and can’t be opened. You should move it to the Trash.

**Comment by ankurk91** [comment]
Duplicate of https://github.com/ankurk91/google-chat-electron/issues/78

I wish if you know there is a Readme file in this repo and there are instructions for mac

**Comment by snorbik** [comment]
As it worked before and stopped working after update, I didnt know I have to run attributes command again.

**Comment by ankurk91** [comment]
You can uninstall the app with brew and re-install it with given command in readme.md.

**Comment by ankurk91** [comment]
I don't see any change in brew formula which should cause the issue.

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/google-chat-electron.rb
