### ISSUE TITLE
Notification Badge

### ISSUE THREAD

**Issue by thamjidm** [ankurk91/google-chat-electron#96]
### Platform

If someone message while we are same his chat box, it can be read.but, still notification badge is ON.

google-chat-electron 2.16.1
Electron 19.0.1
linux 5.13.0-51-generic
Locale: en-GB

**Comment by ankurk91** [comment]
I wish if you an explain the issue in detail.

Do you mean "unread message counter" in dock icon?
The counter never decrease , even if you read the message?

**Comment by thamjidm** [comment]
When if if you got a new message you will get the a notification, bold the name of sender, notification count (badge) will be shown even if we already in sender's chat box.
![1655710944918](https://user-images.githubusercontent.com/105704313/174568670-ea2dbe1a-7956-425e-888b-1eb52cdd0c1c.jpeg)

After switching the chat box, it remains the same.
![1655710944910](https://user-images.githubusercontent.com/105704313/174568981-a97105db-8e9f-4258-8534-7c7d9d9fd565.jpeg)

whenever we switch back to sender's chat box again, it marked as.

**Comment by thamjidm** [comment]
typo : marked as Read.*

**Comment by ankurk91** [comment]
This app relies on the Google chat interface to determine the number of unread messages, in your case the message is in unread state.

You must blame Google for this behavior.

**Comment by thamjidm** [comment]
Who am  I blaming Now ??
