### ISSUE TITLE
How can I financially contribute to this project?

### ISSUE THREAD

**Issue by jedfonner** [ankurk91/google-chat-electron#98]
I'd like to say thanks for this great tool by contributing some cash.  Are you interested in becoming a [Github Sponsor](https://github.com/sponsors) or adding [BuyMeACoffee](https://www.buymeacoffee.com/) integration to the README?

**Comment by ankurk91** [comment]
Thanks your your concerns.
But I dont have time to setup sponser on github.

Additionally my current employer is feeding me with enough money to sustain. 😁

IMO, Open source requires times, money comes at second.
